apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e756oalsq-python 
  janus-idp.io/tekton: e756oalsq-python
  backstage.io/kubernetes-id: e756oalsq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e756oalsq-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  